global using System;
global using System.Linq;
global using System.Linq.Expressions;
global using System.Collections.Generic;
global using Microsoft.Extensions.DependencyInjection;
global using AutoMapper;
global using AutoMapper.Internal;
global using SystemAction = System.Action;
global using SystemType = System.Type;
global using Meow.Infrastructure;