global using System;
global using System.Data.Common;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.EntityFrameworkCore;
global using Npgsql.EntityFrameworkCore.PostgreSQL.Infrastructure;
global using Meow.Helper;
global using Meow.Config;
global using Meow.Extension;
global using Meow.Data.EntityFrameworkCore.Migration;
