global using System;
global using System.Threading.Tasks;
global using System.Collections.Generic;
global using System.Linq;
global using System.Threading;
global using System.Diagnostics;
global using System.Text;
global using System.IO;
global using System.Reflection;
global using System.ComponentModel;
global using System.Globalization;
global using System.Text.Json;
global using System.Linq.Expressions;
global using System.Text.RegularExpressions;
global using System.ComponentModel.DataAnnotations;
global using System.Runtime.InteropServices;
global using System.Text.Encodings.Web;
global using System.Text.Json.Serialization;
global using System.Text.Unicode;
global using System.Buffers;
global using System.Diagnostics.CodeAnalysis;
global using System.Net;
global using System.Net.Http;
global using System.Net.Http.Headers;
global using System.Security.Cryptography.X509Certificates;
global using System.Xml;
global using System.Xml.Linq;
global using System.Data;
global using System.Data.Common;
global using System.Numerics;
global using System.Security.Cryptography;
global using System.Collections;
global using System.Net.NetworkInformation;
global using System.Net.Sockets;
global using System.Web;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Logging.Abstractions;
global using Microsoft.Extensions.DependencyInjection.Extensions;
global using Microsoft.AspNetCore.Hosting;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Http.Extensions;
global using RSAExtensions;
global using SystemType = System.Type;
global using SystemException = System.Exception;
global using SystemDataTable = System.Data.DataTable;
global using SystemExpression = System.Linq.Expressions.Expression;
global using SystemStream = System.IO.Stream;
global using SystemAction = System.Action;